resolver: lts-6.1
packages:
- '.'
- location:
    git: git@github.com:yurrriq/CoreErlang
    commit: 18a02b19ae74f7e29aa31b88d8276c308dcbd234

extra-deps:
- idris-0.12
- megaparsec-5.0.1
# - CoreErlang-0.0.3
