resolver: lts-6.1
packages:
- '.'
- location:
    git: git@github.com:yurrriq/CoreErlang
    commit: 5d6a3b147942e2ade6ea5c104774ac75f95dfde6
  extra-dep: true

extra-deps:
- idris-0.12
- megaparsec-5.0.1
